<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Beheer\Module'                        => __DIR__ . '/Module.php',
    'Beheer\Controller\BeheerController' => __DIR__ . '/src/Beheer/Controller/BeheerController.php',
    'BeheerTest\Framework\TestCase'        => __DIR__ . '/tests/Beheer/Framework/TestCase.php',
    'BeheerTest\SampleTest'                => __DIR__ . '/tests/Beheer/SampleTest.php',
);
