<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Game\Module'                        => __DIR__ . '/Module.php',
    'Game\Controller\GameController' => __DIR__ . '/src/Game/Controller/GameController.php',
    'GameTest\Framework\TestCase'        => __DIR__ . '/tests/Game/Framework/TestCase.php',
    'GameTest\SampleTest'                => __DIR__ . '/tests/Game/SampleTest.php',
);
